name: Release Please

on:
  push:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    name: Create release pull request
    runs-on: ubuntu-latest
    steps:
      # To manually set a release version, add "Release-As: x.y.z" to a commit body.
      - uses: googleapis/release-please-action@v4
        with:
          release-type: simple
